modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="beginning"
version="1.0.0"
displayName="Beginning"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gamer, MCreator"

[[dependencies.beginning]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




